// Code generated by goctl. DO NOT EDIT.
package types

type GroupCreateRequest struct {
	UserID     uint   `header:"User-ID"`
	Mode       int8   `json:"mode,optional"`
	Name       string `json:"name,optional"`
	IsSearch   bool   `json:"is_seatch,optional"`
	Size       int    `json:"size,optional"`
	UserIDList []uint `json:"user_id_list,optional"`
}

type GroupCreateResponse struct {
}
