// Code generated by goctl. DO NOT EDIT.
package types

type OpenLoginInfoResponse struct {
	Name string `json:"name"` //
	Icon string `json:"icon"` //
	Href string `json:"href"` //
}

type SettingsInfoRequest struct {
}

type SettingsInfoResponse struct {
	Site string `json:"site"`
	QQ   string `json:"qq"`
}
