// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.3
// source: settings_rpc.proto

package settings_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SettingsInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SettingsInfoRequest) Reset() {
	*x = SettingsInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settings_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsInfoRequest) ProtoMessage() {}

func (x *SettingsInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settings_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsInfoRequest.ProtoReflect.Descriptor instead.
func (*SettingsInfoRequest) Descriptor() ([]byte, []int) {
	return file_settings_rpc_proto_rawDescGZIP(), []int{0}
}

type SettingsInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` //返回json数据
}

func (x *SettingsInfoResponse) Reset() {
	*x = SettingsInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_settings_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SettingsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsInfoResponse) ProtoMessage() {}

func (x *SettingsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settings_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsInfoResponse.ProtoReflect.Descriptor instead.
func (*SettingsInfoResponse) Descriptor() ([]byte, []int) {
	return file_settings_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *SettingsInfoResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_settings_rpc_proto protoreflect.FileDescriptor

var file_settings_rpc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72,
	0x70, 0x63, 0x22, 0x15, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x2a, 0x0a, 0x14, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x61, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67,
	0x73, 0x12, 0x55, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f,
	0x72, 0x70, 0x63, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x10, 0x5a, 0x0e, 0x2e, 0x2f, 0x73, 0x65,
	0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_settings_rpc_proto_rawDescOnce sync.Once
	file_settings_rpc_proto_rawDescData = file_settings_rpc_proto_rawDesc
)

func file_settings_rpc_proto_rawDescGZIP() []byte {
	file_settings_rpc_proto_rawDescOnce.Do(func() {
		file_settings_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_settings_rpc_proto_rawDescData)
	})
	return file_settings_rpc_proto_rawDescData
}

var file_settings_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_settings_rpc_proto_goTypes = []interface{}{
	(*SettingsInfoRequest)(nil),  // 0: settings_rpc.SettingsInfoRequest
	(*SettingsInfoResponse)(nil), // 1: settings_rpc.SettingsInfoResponse
}
var file_settings_rpc_proto_depIdxs = []int32{
	0, // 0: settings_rpc.Settings.SettingsInfo:input_type -> settings_rpc.SettingsInfoRequest
	1, // 1: settings_rpc.Settings.SettingsInfo:output_type -> settings_rpc.SettingsInfoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_settings_rpc_proto_init() }
func file_settings_rpc_proto_init() {
	if File_settings_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_settings_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettingsInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_settings_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SettingsInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_settings_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settings_rpc_proto_goTypes,
		DependencyIndexes: file_settings_rpc_proto_depIdxs,
		MessageInfos:      file_settings_rpc_proto_msgTypes,
	}.Build()
	File_settings_rpc_proto = out.File
	file_settings_rpc_proto_rawDesc = nil
	file_settings_rpc_proto_goTypes = nil
	file_settings_rpc_proto_depIdxs = nil
}
