// Code generated by goctl. DO NOT EDIT.
// Source: settings_rpc.proto

package server

import (
	"context"

	"FIM/fim_settings/settings_rpc/internal/logic"
	"FIM/fim_settings/settings_rpc/internal/svc"
	"FIM/fim_settings/settings_rpc/types/settings_rpc"
)

type SettingsServer struct {
	svcCtx *svc.ServiceContext
	settings_rpc.UnimplementedSettingsServer
}

func NewSettingsServer(svcCtx *svc.ServiceContext) *SettingsServer {
	return &SettingsServer{
		svcCtx: svcCtx,
	}
}

func (s *SettingsServer) SettingsInfo(ctx context.Context, in *settings_rpc.SettingsInfoRequest) (*settings_rpc.SettingsInfoResponse, error) {
	l := logic.NewSettingsInfoLogic(ctx, s.svcCtx)
	return l.SettingsInfo(in)
}
