// Code generated by goctl. DO NOT EDIT.
package types

type AuthenticationRequest struct {
	Token     string `header:"token,optional"`
	ValidPath string `header:"valid_path,optional"`
}

type AuthenticationResponse struct {
	UserID uint `json:"user_id"`
	Role   int  `json:"role"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type OpenLoginRequest struct {
	Code string `json:"code"`
	Flag string `json:"flag"` //登陆标志，标志是什么登录
}
