// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Admin "FIM/fim_chat/chat_api/internal/handler/Admin"
	"FIM/fim_chat/chat_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/api/chat/chat_delete",
				Handler: chat_deleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/chat_history",
				Handler: chat_historyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/chat_session",
				Handler: chat_sessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/user_top",
				Handler: user_topHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/ws/chat",
				Handler: chat_Handler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/chat/admin/history",
					Handler: Admin.Chat_admin_historyHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/chat/admin/session",
					Handler: Admin.Chat_admin_sessionHandler(serverCtx),
				},
			}...,
		),
	)
}
