// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FIM/fim_chat/chat_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/chat_history",
				Handler: chat_historyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/chat/chat_session",
				Handler: chat_sessionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/chat/user_top",
				Handler: user_topHandler(serverCtx),
			},
		},
	)
}
