// Code generated by goctl. DO NOT EDIT.
// Source: settings_rpc.proto

package settings

import (
	"context"

	"FIM/fim_settings/settings_rpc/types/settings_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SettingsInfoRequest  = settings_rpc.SettingsInfoRequest
	SettingsInfoResponse = settings_rpc.SettingsInfoResponse

	Settings interface {
		SettingsInfo(ctx context.Context, in *SettingsInfoRequest, opts ...grpc.CallOption) (*SettingsInfoResponse, error)
	}

	defaultSettings struct {
		cli zrpc.Client
	}
)

func NewSettings(cli zrpc.Client) Settings {
	return &defaultSettings{
		cli: cli,
	}
}

func (m *defaultSettings) SettingsInfo(ctx context.Context, in *SettingsInfoRequest, opts ...grpc.CallOption) (*SettingsInfoResponse, error) {
	client := settings_rpc.NewSettingsClient(m.cli.Conn())
	return client.SettingsInfo(ctx, in, opts...)
}
