// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FIM/fim_logs/log_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodDelete,
					Path:    "/api/logs/log_delete",
					Handler: log_deleteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/logs/log_list",
					Handler: log_listHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/api/logs/log_read/:id",
					Handler: log_readHandler(serverCtx),
				},
			}...,
		),
	)
}
