// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Admin "FIM/fim_settings/settings_api/internal/handler/Admin"
	"FIM/fim_settings/settings_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/settings/info",
				Handler: settings_infoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/settings/open_login",
				Handler: open_login_infoHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPut,
					Path:    "/api/settings/info/update",
					Handler: Admin.Settings_info_updateHandler(serverCtx),
				},
			}...,
		),
	)
}
