// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	Admin "FIM/fim_file/file_api/internal/handler/Admin"
	"FIM/fim_file/file_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/file/:FileName",
				Handler: file_showHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/file",
				Handler: fileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/image",
				Handler: imageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AdminMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/api/file/list",
					Handler: Admin.File_listHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/api/file/list/remove",
					Handler: Admin.File_list_removeHandler(serverCtx),
				},
			}...,
		),
	)
}
