// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FIM/fim_file/file_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/file/:FileName",
				Handler: file_showHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/file",
				Handler: fileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/file/image",
				Handler: imageHandler(serverCtx),
			},
		},
	)
}
