// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"FIM/fim_user/user_api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/add_friend",
				Handler: add_friendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_info",
				Handler: friend_infoHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/friend_list",
				Handler: friend_listHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/friend_notice_update",
				Handler: friend_notice_updateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/search",
				Handler: searchHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/user_info",
				Handler: user_infoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/user_update",
				Handler: user_updateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/user_valid",
				Handler: user_validHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/user_valid_list",
				Handler: user_valid_listHandler(serverCtx),
			},
		},
	)
}
