// Code generated by goctl. DO NOT EDIT.
package types

type FileListInfoResponse struct {
	FileName  string `json:"file_name"` // 文件名称
	Size      int64  `json:"size"`      // 文件大小
	Path      string `json:"path"`      // 文件的实际路径
	CreatedAt string `json:"created_at"`
	ID        uint   `json:"id"`
	WebPath   string `json:"web_path"` //访问路径
}

type FileListRemoveRequest struct {
	IDList []uint `json:"id_list"`
}

type FileListRemoveResponse struct {
}

type FileListRequest struct {
	Page  int    `form:"page,optional"`
	Limit int    `form:"limit,optional"`
	Key   string `form:"key,optional"`
}

type FileListResponse struct {
	List  []FileListInfoResponse `json:"list"`
	Count int                    `json:"count"`
}

type FileRequest struct {
	UserID uint `header:"User-ID"`
}

type FileResponse struct {
	Src string `json:"src"`
}

type FileShowRequest struct {
	FileName string `path:"FileName"`
}

type ImageRequest struct {
	UserID uint `header:"User-ID"`
}

type ImageResponse struct {
	Url string `json:"url"`
}
