Name: settingsrpc.rpc
ListenOn: 0.0.0.0:30025
Etcd:
  Hosts:
  - 172.29.224.1:2379
  Key: settingsrpc.rpc
Mysql:
  DataSource: root:1310138359@tcp(172.29.224.1:3306)/fim_server_db?charset=utf8mb4&parseTime=True&loc=Local
Log:
  Encoding: plain
  TimeFormat: 2006-01-02 15:04:05
  Stat: false
